//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcServerFinder.Contracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchOptions", Namespace="http://schemas.datacontract.org/2004/07/CalcServerFinder.Contracts")]
    public partial class SearchOptions : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string VersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IProcessingServiceFinder")]
public interface IProcessingServiceFinder
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingServiceFinder/Search", ReplyAction="http://tempuri.org/IProcessingServiceFinder/SearchResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="addresses")]
    System.Uri[] Search(CalcServerFinder.Contracts.SearchOptions options);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProcessingServiceFinderChannel : IProcessingServiceFinder, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProcessingServiceFinderClient : System.ServiceModel.ClientBase<IProcessingServiceFinder>, IProcessingServiceFinder
{
    
    public ProcessingServiceFinderClient()
    {
    }
    
    public ProcessingServiceFinderClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProcessingServiceFinderClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProcessingServiceFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProcessingServiceFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Uri[] Search(CalcServerFinder.Contracts.SearchOptions options)
    {
        return base.Channel.Search(options);
    }
}
