//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcServer.Contracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskData", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public partial class TaskData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentsField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskState", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public enum TaskState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ready = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Started = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskResults", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public partial class TaskResults : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContentsField;
        
        private System.TimeSpan ElapsedTimeField;
        
        private CalcServer.Contracts.TaskErrorInfo[] EncounteredErrorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ElapsedTime
        {
            get
            {
                return this.ElapsedTimeField;
            }
            set
            {
                this.ElapsedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CalcServer.Contracts.TaskErrorInfo[] EncounteredErrors
        {
            get
            {
                return this.EncounteredErrorsField;
            }
            set
            {
                this.EncounteredErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public partial class TaskErrorInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CalcServer.Contracts.TaskErrorCode CodeField;
        
        private string DetailsField;
        
        private string IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CalcServer.Contracts.TaskErrorCode Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskErrorCode", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public enum TaskErrorCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentReadDataFailed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentProcessingFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentWriteResultFailed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentUnknownError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private CalcServer.Contracts.ServiceFaultCode CodeField;
        
        private string IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CalcServer.Contracts.ServiceFaultCode Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFaultCode", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    public enum ServiceFaultCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskGenerateRequestIdFailed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiveTaskDataFailed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskDataFormatError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ComponentUnavailable = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaskResultsNotFound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendTaskResultsFailed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 7,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IProcessingService")]
public interface IProcessingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/QueryForResource", ReplyAction="http://tempuri.org/IProcessingService/QueryForResourceResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="enabled")]
    bool QueryForResource(string name, string version);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/QueryForEnabledResources", ReplyAction="http://tempuri.org/IProcessingService/QueryForEnabledResourcesResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="resources")]
    string[] QueryForEnabledResources();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/SubmitData", ReplyAction="http://tempuri.org/IProcessingService/SubmitDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(CalcServer.Contracts.ServiceFault), Action="http://tempuri.org/IProcessingService/SubmitDataServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="id")]
    string SubmitData(CalcServer.Contracts.TaskData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/GetState", ReplyAction="http://tempuri.org/IProcessingService/GetStateResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="state")]
    CalcServer.Contracts.TaskState GetState(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/GetResults", ReplyAction="http://tempuri.org/IProcessingService/GetResultsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(CalcServer.Contracts.ServiceFault), Action="http://tempuri.org/IProcessingService/GetResultsServiceFaultFault", Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CalcServer.Contracts")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="results")]
    CalcServer.Contracts.TaskResults GetResults(string id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProcessingServiceChannel : IProcessingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProcessingServiceClient : System.ServiceModel.ClientBase<IProcessingService>, IProcessingService
{
    
    public ProcessingServiceClient()
    {
    }
    
    public ProcessingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool QueryForResource(string name, string version)
    {
        return base.Channel.QueryForResource(name, version);
    }
    
    public string[] QueryForEnabledResources()
    {
        return base.Channel.QueryForEnabledResources();
    }
    
    public string SubmitData(CalcServer.Contracts.TaskData data)
    {
        return base.Channel.SubmitData(data);
    }
    
    public CalcServer.Contracts.TaskState GetState(string id)
    {
        return base.Channel.GetState(id);
    }
    
    public CalcServer.Contracts.TaskResults GetResults(string id)
    {
        return base.Channel.GetResults(id);
    }
}
